[package]
name = "cph-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
reqwest.workspace = true
once_cell.workspace = true
dirs.workspace = true
toml.workspace = true
anyhow.workspace = true
regex.workspace = true
log.workspace = true
axum = { version = "0.7.5", features = ["default"] }
hyper = { version = "1.4.1", features = ["full"] }
fs2 = { version = "0.4.3" }

icpc-project-gen = { path = "../icpc-project-gen" }
